### ISSUE TITLE
I have a question about code

### ISSUE THREAD

**Issue by Solight96** [Cheeun/DAQ-pytorch#1]
Hello.
I have a question.
When I run 'train_EDSR_x4.sh' file. I'm getting an error as shown in the picture below.
<img width="666" alt="error1" src="https://user-images.githubusercontent.com/58461685/173514533-d44e032b-b16a-4d84-a0c7-6a1223fb9979.png">
Do you know how to fix this error?

**Comment by Cheeun** [comment]
Hello.
I have some questions.
Did you use the provided conda environment file to set up the environment?
Also, could you check if your datasets are in the right format?
For example, image files inside DIV2K/DIV2K_train_LR_bicubic/X4 should be named like 0001x4.png, 0002x4.png, and so on. 
Thanks!

**Comment by Solight96** [comment]
Yes. 
I set the conda environment as instructed in your 'readme.md' file and set the dataset to the correct format.
If the --ext option is set to 'bin' instead of 'sep', The code seems to run normally. Is there any difference in performance if I use '--ext bin' option?
thank you.

**Comment by Solight96** [comment]
Additionally, if I run the code with the '--ext bin' option, it seems that the qualitative result is not very good. Is there any solution?

**Comment by Cheeun** [comment]
Hello, sorry for the late reply.
The --ext option is a way to fetch dataset files and bin type just enables a faster fetch.
Thus, changing the --ext option will **not** incur a difference in performance.
Thanks!
