### ISSUE TITLE
A question about the missing QQ of mean in the network. 

### ISSUE THREAD

**Issue by LuletterSoul** [Cheeun/DAQ-pytorch#2]
Hello, thank you for your excellent work. I would like to ask, the paper mentioned that the mean and variance need to be quantized twice, but I did not find mu_mu, sig_mu in the code actually. Did I miss something?

**Comment by Cheeun** [comment]
Hello thanks for your interest in our work and sorry for the delayed response!
Unlike quantizing the variance, quantizing the mean gives minimal computation reduction with a minimal accuracy loss.
(Please refer to Section 3.3.1 in our paper to see why it hardly impacts the overall computations.)
Hence, it was not included in this repository, but we will update it.
Thanks for pointing it out!
