### ISSUE TITLE
Checkpoints for testing

### ISSUE THREAD

**Issue by makhovds** [Cheeun/DAQ-pytorch#3]
Good day! Thank you for interesting work on quantization, could you please upload final checkpoints for your DAQ method for different bitwidths? In the link you have attached there is only one checkpoint for starting training.

Thanks in advance!

**Comment by Cheeun** [comment]
Thanks for your interest in our work! 
I will upload checkpoints for different bit-widths and then let you know in this thread!

**Comment by Cheeun** [comment]
Hi, sorry for the delay! I uploaded the checkpoints for different bit-widths in the link. 
Please take a look!
